services:
  - type: web
    name: anemia-detection-ai-1
    runtime: docker
    dockerfilePath: inference/Dockerfile
    envVars:
      - key: HF_CONJ_MODEL_REPO
        value: hssling/anemia-efficientnet-b4-conjunctiva
      - key: HF_NAIL_MODEL_REPO
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: ENSEMBLE_W_CONJ
        value: "1.0"
      - key: ENSEMBLE_W_NAIL
        value: "0.0"
      - key: PRELOAD_MODELS
        value: "0"
      - key: ENABLE_GRADIO
        value: "0"
    healthCheckPath: /health
    plan: free
